site_name: BiWAKO

theme:
  name: "material"
  icon:
    logo: material/fish

  palette:
    - media: "(prefers-color-scheme: light)"
      primary: light blue
      accent: green
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: light blue
      accent: green
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

repo_url: https://github.com/NMZ0429/BiWAKO
repo_name: NMZ0429/BiWAKO

nav:
  - "Home": index.md
  - "Model":
      - "Mono Depth Prediction": models/mono_depth.md
      - "Object Detection": models/obj_det.md
      - "Super Resolution": models/super_resolution.md
      - "Human Portrait Segmentation": models/human_seg.md
      - "Denoise Image": models/denoising.md
      - "Style Transfer": models/style_transfer.md
      - "Salient Object Segmenation": models/salient_det.md
      - "Emotion Recognition": models/emotion.md
      - "Face Detection": models/face_det.md
      - "Human Parsing": models/human_parsing.md
      - "Image Classification": models/image_clf.md
      - "Semantic Segmentation": models/semantic_seg.md
      - "Diver's View Segmentation": models/suim_net.md
  - "API":
      - "APIs": api/index.md
      - "Video Prediction": api/video_predictor.md
  - "Demo":
      - "Use Demo Scripts": demo/index.md

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  - attr_list
  - md_in_html

extra:
  generator: false
